name: 'React Project Checker'
description: 'Checks a React project for bad code and leaves suggestions to fix'
author: 'Victor Danilov'

branding:
  icon: 'check-square'
  color: 'green'

runs:
  using: 'composite'
  steps:
    - name: Install React Project Checker Dependencies
      shell: bash
      run: npm ci --prefix $GITHUB_ACTION_PATH/dist
    - name: Save Code Linting Report JSON
      shell: bash
      run: $GITHUB_ACTION_PATH/dist/node_modules/.bin/eslint --config $GITHUB_ACTION_PATH/dist/.eslintrc.cjs --output-file eslint_report.json --format json src
      continue-on-error: true
    - name: Annotate Code Linting Results
      uses: ataylorme/eslint-annotate-action@v2
      with:
        repo-token: '${{ github.token }}'
        report-json: 'eslint_report.json'
        markdown-report-on-step-summary: true
      continue-on-error: true
    - name: Check React Project Rules
      shell: bash
      run: 'node dist/index.js'
      env:
        TOKEN: '${{ github.token }}'
